/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import Modelo.Cliente;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author facue
 */
public class modificarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form modificarCliente
     */
    public modificarCliente() {
        initComponents();
    }
    private Controlador controlador;

    public Controlador getControlador() {
        return controlador;
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtModificarApellido = new javax.swing.JTextField();
        txtModificarNombre = new javax.swing.JTextField();
        txtModificarDni = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("Nuevo nombre");

        jLabel2.setText("Nuevo apellido");

        jLabel3.setText("Nuevo dni");

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModificarDni, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModificarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btnModificar)))
                .addGap(0, 51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModificarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModificarDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
     if (controlador.getModelo().actualizarCliente(controlador.getModelo().getClienteAux()))
     {
         JOptionPane.showMessageDialog(null, "Modificado con éxito");
     }
     else
     {
         JOptionPane.showMessageDialog(null, "No se ha modificado");
     }
     
    }//GEN-LAST:event_btnModificarActionPerformed

    public JTextField getTxtModificarApellido() {
        return txtModificarApellido;
    }

    public void setTxtModificarApellido(JTextField txtModificarApellido) {
        this.txtModificarApellido = txtModificarApellido;
    }

    public JTextField getTxtModificarDni() {
        return txtModificarDni;
    }

    public void setTxtModificarDni(JTextField txtModificarDni) {
        this.txtModificarDni = txtModificarDni;
    }

    public JTextField getTxtModificarNombre() {
        return txtModificarNombre;
    }

    public void setTxtModificarNombre(JTextField txtModificarNombre) {
        this.txtModificarNombre = txtModificarNombre;
    }

    public JTextField getBtnModificarApellido() {
        return txtModificarApellido;
    }

    public void setBtnModificarApellido(JTextField btnModificarApellido) {
        this.txtModificarApellido = btnModificarApellido;
    }

    public JTextField getBtnModificarDni() {
        return txtModificarDni;
    }

    public void setBtnModificarDni(JTextField btnModificarDni) {
        this.txtModificarDni = btnModificarDni;
    }

    public JTextField getBtnModificarNombre() {
        return txtModificarNombre;
    }

    public void setBtnModificarNombre(JTextField btnModificarNombre) {
        this.txtModificarNombre = btnModificarNombre;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtModificarApellido;
    private javax.swing.JTextField txtModificarDni;
    private javax.swing.JTextField txtModificarNombre;
    // End of variables declaration//GEN-END:variables
}
