/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import Modelo.Cliente;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author facue
 */
public class remitosVer extends javax.swing.JInternalFrame {

    public JTable getTablaClientesRemito() {
        return tablaClientesRemito;
    }

    public void setTablaClientesRemito(JTable tablaClientesRemito) {
        this.tablaClientesRemito = tablaClientesRemito;
    }

    public JTable getTablaRemitos() {
        return tablaRemitos;
    }

    public void setTablaRemitos(JTable tablaRemitos) {
        this.tablaRemitos = tablaRemitos;
    }
 private Controlador controlador;

    public Controlador getControlador() {
        return controlador;
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }
 
    /**
     * Creates new form remitosVer
     */
    public remitosVer() {
        initComponents();
        this.setTitle("Remitos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientesRemito = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaRemitos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);

        tablaClientesRemito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NumeroCliente", "Nombre", "Apellido", "Dni"
            }
        ));
        tablaClientesRemito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClientesRemitoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaClientesRemito);

        tablaRemitos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NumeroRemito", "NumeroCliente", "Fecha", "Importe", "EstadoPago"
            }
        ));
        tablaRemitos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaRemitosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaRemitos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaRemitosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaRemitosMouseClicked

    }//GEN-LAST:event_tablaRemitosMouseClicked

    private void tablaClientesRemitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesRemitoMouseClicked
       int fila= tablaClientesRemito.getSelectedRow();
       if (fila==-1){
           JOptionPane.showMessageDialog(null,"Usuario no seleccionado");
       }else{
           int id= Integer.parseInt(tablaClientesRemito.getValueAt(fila,0).toString());
           String nombre= (String)tablaClientesRemito.getValueAt(fila,1);
           String apellido= (String)tablaClientesRemito.getValueAt(fila,2);
           int dni= Integer.parseInt(tablaClientesRemito.getValueAt(fila,3).toString());
           Cliente cli = new Cliente(id,nombre,apellido,dni);
           controlador.getModelo().setClienteAux(cli);
           controlador.getModelo().listarRemitos(tablaRemitos, cli);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tablaClientesRemitoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaClientesRemito;
    private javax.swing.JTable tablaRemitos;
    // End of variables declaration//GEN-END:variables
}
